# Generated by Django 3.2.4 on 2021-07-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('hash', models.CharField(blank=True, max_length=32, null=True)),
                ('tx_id', models.CharField(blank=True, max_length=66, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
