# Generated by Django 3.2.4 on 2021-07-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210707_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tx_id',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
