# Generated by Django 3.2.4 on 2021-07-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='post_content',
        ),
    ]
