# Generated by Django 3.2.4 on 2021-07-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_content_post_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_content',
            new_name='post_message',
        ),
    ]
