# Generated by Django 3.2.4 on 2021-07-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_post_content_post_post_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
