# Generated by Django 3.2.4 on 2021-07-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginactivity',
            name='alert',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
