# Generated by Django 3.2.4 on 2021-07-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userloginactivity_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginactivity',
            name='alert',
            field=models.BooleanField(default=False),
        ),
    ]
